// Code generated by mockery v2.10.0. DO NOT EDIT.

package github

import mock "github.com/stretchr/testify/mock"

// Mock is an autogenerated mock type for the Client type
type Mock struct {
	mock.Mock
}

// PullRequestBody provides a mock function with given fields: number
func (_m *Mock) PullRequestBody(number int) (string, error) {
	ret := _m.Called(number)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(number)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
